/* Standalone C-only system (no scripting layer).
 *   This source has been autogenerated
 *     from a usc system description.
 *    Autogenerated with generate_capp tool.
 */

#include <ubx.h>

/* Additional header files for types */


int main(int argc, char **argv)
{
  int len, ret=EXIT_FAILURE;
  ubx_node_info_t ni;
//   char* tmp_char;
  /* initalize the node */
  ubx_node_init(&ni, "rsg_bridge_test_app");
  ubx_data_t *d;
  ubx_block_t *rsgrecieverB_4;
  ubx_block_t *publisherB_7;
  ubx_block_t *rsgrecieverA_2;
  ubx_block_t *rsgsenderA_1;
  ubx_block_t *subscriberA_6;
  ubx_block_t *subscriberB_8;
  ubx_block_t *publisherA_5;
  ubx_block_t *rsgsenderB_3;
  ubx_block_t *scenesetup_9;
  ubx_block_t *webif;

  /* Load Modules
   *
   * Paths have to be adopted accodingly!
   */
  if(ubx_module_load(&ni, "/opt/src/sandbox/ubx_team_microblox/microblx/std_types/stdtypes/stdtypes.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/ubx_team_microblox/microblx/std_blocks/ptrig/ptrig.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/ubx_team_microblox/microblx/std_blocks/lfds_buffers/lfds_cyclic.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/ubx_team_microblox/microblx/std_blocks/logging/file_logger.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/microblx_install/lib/microblx/blocks/irospublisher.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/microblx_install/lib/microblx/blocks/irossubscriber.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/microblx_install/lib/microblx/types/rsg_types.so") != 0)
    goto out;
  
  if(ubx_module_load(&ni, "/opt/src/sandbox/ubx_team_microblox/microblx/std_blocks/webif/webif.so") != 0)
    goto out;

  if(ubx_module_load(&ni, "/opt/src/sandbox/microblx_install/lib/microblx/blocks/rsgrecieverlib.so") != 0)
    goto out;

  if(ubx_module_load(&ni, "/opt/src/sandbox/microblx_install/lib/microblx/blocks/rsgsenderlib.so") != 0)
    goto out;

  printf("All modules have been loaded!\n");
  
  /* Create blocks */
  /* create rsgsenderA block, instance of rsg_sender */
  if((rsgsenderA_1 = ubx_block_create(&ni, "rsg_sender", "rsgsenderA_1"))==NULL)
    goto out;
    
  /* create rsgrecieverA block, instance of rsg_reciever */
  if((rsgrecieverA_2 = ubx_block_create(&ni, "rsg_reciever", "rsgrecieverA_2"))==NULL)
    goto out;
    
  /* create rsgsenderB block, instance of rsg_sender */
  if((rsgsenderB_3 = ubx_block_create(&ni, "rsg_sender", "rsgsenderB_3"))==NULL)
    goto out;
    
  /* create rsgrecieverB block, instance of rsg_reciever */
  if((rsgrecieverB_4 = ubx_block_create(&ni, "rsg_reciever", "rsgrecieverB_4"))==NULL)
    goto out;
    
  /* create publisherA block, instance of rosbridge/publisher */
  if((publisherA_5 = ubx_block_create(&ni, "rosbridge/publisher", "publisherA_5"))==NULL)
    goto out;
    
  /* create subscriberA block, instance of rosbridge/subscriber */
  if((subscriberA_6 = ubx_block_create(&ni, "rosbridge/subscriber", "subscriberA_6"))==NULL)
    goto out;
    
  /* create publisherB block, instance of rosbridge/publisher */
  if((publisherB_7 = ubx_block_create(&ni, "rosbridge/publisher", "publisherB_7"))==NULL)
    goto out;
    
  /* create subscriberB block, instance of rosbridge/subscriber */
  if((subscriberB_8 = ubx_block_create(&ni, "rosbridge/subscriber", "subscriberB_8"))==NULL)
    goto out;
    
  /* create scenesetup block, instance of rsg_scene_setup */
//  if((scenesetup_9 = ubx_block_create(&ni, "rsg_scene_setup", "scenesetup_9"))==NULL)
//    goto out;
  
  if((webif = ubx_block_create(&ni, "webif/webif", "webif"))==NULL)
    goto out;

  printf("All modules have been created!\n");
  
  /* Configure blocks */
    /* configuration of publisherA_5  */
        
  d = ubx_config_get_data(publisherA_5,"topic_name");
  ubx_data_resize(d,strlen("mytopic_forwards")+1);
  strncpy(d->data,"mytopic_forwards",strlen("mytopic_forwards")+1);

  /* configuration of publisherB_7  */
        
  d = ubx_config_get_data(publisherB_7,"topic_name");
  ubx_data_resize(d,strlen("mytopic_backwards")+1);
  strncpy(d->data,"mytopic_backwards",strlen("mytopic_backwards")+1);

  /* configuration of subscriberA_6  */
        
  d = ubx_config_get_data(subscriberA_6,"topic_name");
  ubx_data_resize(d,strlen("mytopic_backwards")+1);
  strncpy(d->data,"mytopic_backwards",strlen("mytopic_backwards")+1);

        
//  d = ubx_config_get_data(subscriberA_6,"trig_blocks");
//  ubx_data_resize(d,1);
//    memcpy(d->data,
//    ( []){
//      { .b=rsgrecieverA_2, .num_steps=1, .measure=0},
//      { NULL },
//    },
//    sizeof()*1
//  );


  /* configuration of subscriberB_8  */
        
  d = ubx_config_get_data(subscriberB_8,"topic_name");
  ubx_data_resize(d,strlen("mytopic_forwards")+1);
  strncpy(d->data,"mytopic_forwards",strlen("mytopic_forwards")+1);

        
  d = ubx_config_get_data(subscriberB_8,"trig_blocks");
//  ubx_data_resize(d,1);
//    memcpy(d->data,
//    ( []){
//      { .b=rsgrecieverB_4, .num_steps=1, .measure=0},
//      { NULL },
//    },
//    sizeof()*1
//  );




  
  /* Connect blocks            */
  ubx_port_connect_out(ubx_port_get(rsgsenderA_1,"rsg_out" ), publisherA_5 );
  ubx_port_connect_out(ubx_port_get(rsgsenderB_3,"rsg_out" ), publisherB_7 );
  ubx_port_connect_in(ubx_port_get(rsgrecieverA_2,"rsg_in" ), subscriberA_6 ); 
  ubx_port_connect_in(ubx_port_get(rsgrecieverB_4,"rsg_in" ), subscriberB_8 ); 

  /* INIT and START the BLOCKS */
  if(ubx_block_init(rsgrecieverB_4) != 0) {
    ERR("failed to init rsgrecieverB_4");
    goto out;
  }
  if(ubx_block_init(publisherB_7) != 0) {
    ERR("failed to init publisherB_7");
    goto out;
  }
  if(ubx_block_init(rsgrecieverA_2) != 0) {
    ERR("failed to init rsgrecieverA_2");
    goto out;
  }
  if(ubx_block_init(rsgsenderA_1) != 0) {
    ERR("failed to init rsgsenderA_1");
    goto out;
  }
  if(ubx_block_init(subscriberA_6) != 0) {
    ERR("failed to init subscriberA_6");
    goto out;
  }
  if(ubx_block_init(subscriberB_8) != 0) {
    ERR("failed to init subscriberB_8");
    goto out;
  }
  if(ubx_block_init(publisherA_5) != 0) {
    ERR("failed to init publisherA_5");
    goto out;
  }
  if(ubx_block_init(rsgsenderB_3) != 0) {
    ERR("failed to init rsgsenderB_3");
    goto out;
  }
//  if(ubx_block_init(scenesetup_9) != 0) {
//    ERR("failed to init scenesetup_9");
//    goto out;
//  }
  if(ubx_block_init(webif) != 0) {
    ERR("failed to init webif");
    goto out;
  }

  printf("All blocks have been initialized!\n");

  if(ubx_block_start(rsgrecieverB_4) != 0) {
    ERR("failed to start rsgrecieverB_4");
    goto out;
  }
  if(ubx_block_start(publisherB_7) != 0) {
    ERR("failed to start publisherB_7");
    goto out;
  }
  if(ubx_block_start(rsgrecieverA_2) != 0) {
    ERR("failed to start rsgrecieverA_2");
    goto out;
  }
  if(ubx_block_start(rsgsenderA_1) != 0) {
    ERR("failed to start rsgsenderA_1");
    goto out;
  }
  if(ubx_block_start(subscriberA_6) != 0) {
    ERR("failed to start subscriberA_6");
    goto out;
  }
  if(ubx_block_start(subscriberB_8) != 0) {
    ERR("failed to start subscriberB_8");
    goto out;
  }
  if(ubx_block_start(publisherA_5) != 0) {
    ERR("failed to start publisherA_5");
    goto out;
  }
  if(ubx_block_start(rsgsenderB_3) != 0) {
    ERR("failed to start rsgsenderB_3");
    goto out;
  }
//  if(ubx_block_start(scenesetup_9) != 0) {
//    ERR("failed to start scenesetup_9");
//    goto out;
//  }
  if(ubx_block_start(webif) != 0) {
    ERR("failed to start rsgsenderB_3");
    goto out;
  }
  printf("All blocks have been started!\n");
  
    
  printf("Everything is up and running! hit enter to quit\n");
  getchar();

  ret=EXIT_SUCCESS;
out:
  /* this cleans up all blocks and unloads all modules */
  ubx_node_cleanup(&ni);
  exit(ret);  
}

